[project]
name = "voice-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "customtkinter>=5.2.2",
    "numpy>=2.3.4",
    "pyaudio>=0.2.14",
    "sounddevice>=0.5.2",
]
